### ISSUE TITLE
snapshotting into Trilinos

### ISSUE THREAD

**Issue by nschloe** [gdsjaar/seacas#15]
Now that SEACAS is on GitHub, we can think about how to make it easy to snapshot this repo into Trilinos. @bartlettroscoe has something in place for TriBits and I think this is working pretty smooth. The general storyline would be the following:

* Create a base TriBITS project called `SEACASProj` or something, and then have the base directory organized like:

    ```
  seacas/
    ProjectName.cmake   # SET(PROJECT_NAME SEACASProj)
    PackagesList.cmake  # List two packages, Zoltan, and SEACAS
    TPLsList.camke      # Same as now
    packages/
      seacas/           # Main source for the SEACAS pacakge
      zoltan/           # Snapshot of Zoltan/ dir from Trilinos
    TPL/                # Only externally built TPLs
      cgns/
      …
      serial_mpi/        
    …
```
The rest of the directories would be the same. 

* With this layout, the directory `seacas/packages/seacas/` would be directly snapshotted into Trilinos like:

  ```bash
$ export SEACAS_PROJ=???
$ cd Trilinos/package/seacas/
$ ../../cmake/tribits/python_utils/shapshot-dir.py --orig-dir=$SEACUS_PROJ/packages/seacus/
```

* Then run the `checkin-test.py` script to push.

Bonus Level
----
If we want to allow for local changes to SEACAS in Trilinos, we should snapshot to a branch and them merge like:
```
$ cd Trilinos/package/seacas/
$ git checkout --track origin/seacas-github-snapshot
$ ./snapshot_seacas.sh
$ git push   # to origin/seacas-github-snapshot
$ git checkout master
$ git merge --no-ff seacas
```
That will allow for local urgent changes to `seacas/` in the Trilinos ‘master’ branch to not get overwritten by the snapshot.  The process for moving changes from `Trilinos/packages/secacas/` to `seacas/packages/seacas/` would require using `git format-patch` and `git am` and it would be more fragile because there is no root commit to resolve merge conflicts.

This is about the exactly same [workflow used for TriBITS](http://trac.trilinos.org/wiki/TriBITSTrilinosDev). It is the same in that a subdir from a separate repo is snapshotted into a directory under Trilinos.  That part is exactly the same.

We can also test changes before the snapshot into Trilinos with:
```
    -DSEACAS_SOURCE_DIR=$SEACAS_PROJ/packages/seacas
```

**Comment by gdsjaar** [comment]
I think that the reorganization you show below is good since most of the cmake-related files can be shared between Trilinos and a standalone SEACAS build.  We are also planning on going to the snapshotting mode in the future.  I redid the seacas cmake structure to follow this and it has been committed.

Thanks,
..Greg

--
"A supercomputer is a device for turning compute-bound problems into I/O-bound problems"

**Comment by nschloe** [comment]
Cool! Feel free to close this issue.
