### ISSUE TITLE
Don't need extra var sets in Dependencies.cmake when using TRIBITS_PACKAGE_DEFINE_DEPENDENCIES()

### ISSUE THREAD

**Issue by bartlettroscoe** [gdsjaar/seacas#20]
@gdsjaar,

FYI:

When using the macro [TRIBITS_PACKAGE_DEFINE_DEPENDENCIES()](https://tribits.org/doc/TribitsDevelopersGuide.html#tribits-package-define-dependencies) in a [Dependencies.cmake](https://tribits.org/doc/TribitsDevelopersGuide.html#packagedir-cmake-dependencies-cmake) file, you don't need to set dependency vars anymore.  They all get set in the macro arguments and those that are empty are set to "" automatically.  For example, see [TribitsExampleProject/with_subpackages/cmake/Dependencies.cmake](https://github.com/TriBITSPub/TriBITS/blob/master/tribits/examples/TribitsExampleProject/packages/with_subpackages/cmake/Dependencies.cmake) which shows:

```
TRIBITS_PACKAGE_DEFINE_DEPENDENCIES(
  SUBPACKAGES_DIRS_CLASSIFICATIONS_OPTREQS
    A   a   PT  REQUIRED
    B   b   ST  OPTIONAL
    C   c   ST  OPTIONAL
  )
```

Therefore, in the file [seacas/cmake/Dependencies.cmake](https://github.com/gdsjaar/seacas/blob/master/packages/seacas/cmake/Dependencies.cmake), you don't need to set the vars:

```
SET(LIB_REQUIRED_DEP_PACKAGES)
SET(LIB_OPTIONAL_DEP_PACKAGES)
SET(TEST_REQUIRED_DEP_PACKAGES)
SET(TEST_OPTIONAL_DEP_PACKAGES)
SET(LIB_REQUIRED_DEP_TPLS)
SET(LIB_OPTIONAL_DEP_TPLS MPI)
SET(TEST_REQUIRED_DEP_TPLS)
SET(TEST_OPTIONAL_DEP_TPLS)
```

They get set to empty "" by the macro `TRIBITS_PACKAGE_DEFINE_DEPENDENCIES()` automatically.  This just removes clutter and avoids mistakes (that can be hidden by clutter).

Hope this is helpful.

**Comment by gdsjaar** [comment]
Yes, that is helpful.
Thanks,
..Greg
--
"A supercomputer is a device for turning compute-bound problems into I/O-bound problems"

**Comment by gdsjaar** [comment]
Clarification - Is that just for the top-level Dependencies.cmake, or is that for all of the sub package cmake/Dependencies.cmake.

If they are all empty, can the Dependencies.cmake file be empty (for example, packages/seacas/libraries/svdi/cmake/Dependencies.cmake)

Thanks,
..GReg
--
"A supercomputer is a device for turning compute-bound problems into I/O-bound problems"

**Comment by bartlettroscoe** [comment]
> Clarification - Is that just for the top-level Dependencies.cmake, or is that for all of the sub package cmake/Dependencies.cmake.

You can use the macro `TRIBITS_PACKAGE_DEFINE_DEPENDENCIES()` in all Dependencies.cmake files.

> If they are all empty, can the Dependencies.cmake file be empty (for example, [packages/seacas/libraries/svdi/cmake/Dependencies.cmake](https://github.com/gdsjaar/seacas/blob/master/packages/seacas/libraries/svdi/cmake/Dependencies.cmake))

In the case of [packages/seacas/libraries/svdi/cmake/Dependencies.cmake](https://github.com/gdsjaar/seacas/blob/master/packages/seacas/libraries/svdi/cmake/Dependencies.cmake), you have just a single TPL dependency so this should look like:

```
TRIBITS_PACKAGE_DEFINE_DEPENDENCIES(
  LIB_REQUIRED_TPLS X11
  )
```
Nice and simple, no clutter.

For examples, look at the Dependencies.cmake files under [TribitsExampleProject/packages/with_subpackages/](https://github.com/TriBITSPub/TriBITS/tree/master/tribits/examples/TribitsExampleProject/packages/with_subpackages).

Let me know if you have more questions about this.

**Comment by bartlettroscoe** [comment]
And if a package has no dependencies at all, you still need to call `TRIBITS_PACKAGE_DEFINE_DEPENDENCIES()` but you give it empty arguments like [TribitsHelloWorld/hello_world/cmake/Dependencies.cmake](https://github.com/TriBITSPub/TriBITS/blob/master/tribits/examples/TribitsHelloWorld/hello_world/cmake/Dependencies.cmake) which is:

```
TRIBITS_PACKAGE_DEFINE_DEPENDENCIES()
```
 I will update the documentation to make this clear.

Note that all of these TriBITS examples under tribits/doc/examples/ have automated testing of some type so they should all be correct at all times.

**Comment by gdsjaar** [comment]
This has been applied to all Dependencies.cmake in seacas.  Thanks, it definitely simplifies the files.
