### ISSUE TITLE
heavy documentation

### ISSUE THREAD

**Issue by nschloe** [gdsjaar/seacas#22]
Right now, SEACAS's documentation is almost than half as heavy as the actual packages,
```
$ du -sh *
[...]
28M	doc
[...]
58M	packages
[...]
```
This is mostly due to the presence of some scanned files, e.g., `FASTQ.pdf` at 11MB. Several files exceed 1MB. It'd be probably be worthwhile considering moving those files to another place (e.g., github pages) and linking it from the `README`.

**Comment by gsjaardema** [comment]
Yes, I was actually looking at github pages this morning...

..Greg

**Comment by nschloe** [comment]
Good idea. This is how I'm providing a bunch of large images and data files as well.

**Comment by gsjaardema** [comment]
The initial version should be in place.  I want to do some big improvements
to the layout, but at least the documentation is available.

I also think that I cleaned out the repository (using bfg), but haven't
been able to verify totally that the history of the large files has been
erased.
..Greg

**Comment by nschloe** [comment]
https://gdsjaar.github.io/seacas/ looks great! Closing this
