### ISSUE TITLE
versioning scheme

### ISSUE THREAD

**Issue by nschloe** [gdsjaar/seacas#8]
SEACAS's versioning scheme set the `SEACAS_VERSION` string incorrectly. It is really composed of major and minor version. Compare Trilinos:
```cmake
SET(Trilinos_VERSION 12.5)
SET(Trilinos_MAJOR_VERSION 12)
SET(Trilinos_MAJOR_MINOR_VERSION 120500)
SET(Trilinos_VERSION_STRING "12.5 (Dev)")
```
Besides, a _YEAR.MONTH_ scheme seems to be in place. This is probably to immediately recognize if a version is outdated or not.

However, this approach has flaws. One obvious shortcoming is that you cannot make two releases shortly after one another. More importantly, though, SEACAS is missing out on the [semantic meaning of major and minor versions](http://semver.org/). Typically, a major version change indicates an API change, a minor version indicates that functionality has been added in a backwards-compatible way.

**Comment by gsjaardema** [comment]
Changed.  The cmake-built version has been deemed to start at 2.0
