### ISSUE TITLE
library bundling

### ISSUE THREAD

**Issue by nschloe** [gdsjaar/seacas#9]
I see that SEACAS is bundling a bunch of TPLs. This is probably to make it easier for new users to get started with SEACAS.

However, version bundling has serious downsides:

 * upstream fixes don't automatically make it to SEACAS,
 * SEACAS installations will conflict with upstream installations,
 * bundled software will get tweaked without getting the patches upstream, leading to an unupdatable mess.

I personally just bumped in number 2 with a Trilinos installation; Zoltan is conflicting here.
There are [more elaborate texts on this](https://blog.flameeyes.eu/2009/03/bundling-libraries-the-curse-of-the-ancients#gsc.tab=0).

Of course, we still want to make it easy for newcomers to get started with SEACAS. That's why I prepare a [PPA](https://launchpad.net/~nschloe/+archive/ubuntu/seacas-nightly/+packages), too.

There has to be the possibility to depend on system-installed libraries though, and I'd suggest to make it the default. Then, if anyone pulls
```cmake
-DBUILD_BUNDLED_TPLS:BOOL=ON
```
he or she gets it all.

**Comment by nschloe** [comment]
On a side node, the SEACAS repo is over 300MB large! (Mostly due to Zoltan.)

**Comment by gsjaardema** [comment]
Not sure what the "bunch of files" refers to. I think zoltan is the only
"TPL" that is provided and it internally provides the siMPI
library/facility.

Do you see others that I am missing?
..Greg

**Comment by gsjaardema** [comment]
Zoltan package has been reduced to 51 MB.  I think all of the issues have been addressed other than that zoltan is still packaged with seacas.  For now, I would like to keep it that way to make it easier for users.

**Comment by nschloe** [comment]
Okay. Note that, since these huge files are already in Trilinos history, everyone who ever clones SEACAS will have to download them. Perhaps a case for rewriting history?

Closing.
